[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
futures-util = "0.3.31"
rand = "0.9.2"
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
naori-ai = { path = "../.." }
naori-ai-macros = { path = "../../macros" }
